name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # S'exécute automatiquement toutes les nuits à minuit
  workflow_dispatch: # Vous permet de lancer la mise à jour manuellement d'un clic

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Étape indispensable pour télécharger le code du dépôt dans le runner GitHub
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: affaan-m/ECC
          upstream_sync_branch: main
