name: Auto Sync Fork

on:
  schedule:
    - cron: '10 11 * * *' # S'exécute automatiquement toutes les nuits à minuit
  workflow_dispatch: # Vous permet de lancer la mise à jour manuellement d'un clic

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Force Sync with Upstream
        run: |
          git remote add upstream https://github.com
          git fetch upstream main
          git checkout main
          
          # Aligne votre code sur le dépôt d'origine
          git reset --hard upstream/main
          
          # Pousse les changements en incluant de force votre token de sécurité SYNC_ECC
          git push https://x-access-token:${{ secrets.SYNC_ECC }}@://github.com main --force
